# Generated by Django 3.2 on 2021-05-20 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='astana', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='kz', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='man', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='higher_education',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
