# Generated by Django 3.2 on 2021-04-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='imageURL',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='poll',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
