# Generated by Django 3.2 on 2021-05-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20210430_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollvote',
            name='question_id',
        ),
    ]
