# Generated by Django 3.2 on 2021-05-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20210521_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='passedCounter',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PollStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('womenNum', models.IntegerField(default=0)),
                ('womenPercentage', models.FloatField(default=0.0)),
                ('manNum', models.IntegerField(default=0)),
                ('manPercentage', models.FloatField(default=0.0)),
                ('higher_education_num', models.IntegerField(default=0)),
                ('higher_education_percentage', models.FloatField(default=0.0)),
                ('countryNum', models.IntegerField(default=0)),
                ('countryPercentage', models.FloatField(default=0.0)),
                ('cityNum', models.IntegerField(default=0)),
                ('cityPercentage', models.FloatField(default=0.0)),
                ('averageAge', models.FloatField(default=0.0)),
                ('rateCounter', models.IntegerField(default=0)),
                ('passedCounter', models.IntegerField(default=0)),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
        ),
    ]
