# Generated by Django 3.2 on 2021-05-21 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20210521_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollstats',
            old_name='cityPercentage',
            new_name='countryKZPercentage',
        ),
        migrations.RenameField(
            model_name='pollstats',
            old_name='cityNum',
            new_name='countryNumKZ',
        ),
        migrations.RenameField(
            model_name='pollstats',
            old_name='countryNum',
            new_name='countryNumUSA',
        ),
        migrations.RenameField(
            model_name='pollstats',
            old_name='countryPercentage',
            new_name='countryUSAPercentage',
        ),
    ]
