# Generated by Django 3.2 on 2021-05-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20210521_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollanswer',
            name='votedPercentage',
            field=models.FloatField(default=0.0),
        ),
    ]
