# Generated by Django 3.2 on 2021-05-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_pollanswer_votedpercentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollanswer',
            name='votedPercentage',
        ),
        migrations.AddField(
            model_name='pollanswer',
            name='votedNum',
            field=models.IntegerField(default=0),
        ),
    ]
