# Generated by Django 3.2 on 2021-04-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison_survey', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
