# Generated by Django 3.2 on 2021-05-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison_survey', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.AlterField(
            model_name='comparisonsurvey',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
