# Generated by Django 3.2 on 2021-05-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison_survey', '0002_auto_20210514_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisonsurvey',
            old_name='user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comparisonsurveyresult',
            old_name='rate_object_id',
            new_name='rate_object',
        ),
        migrations.RenameField(
            model_name='comparisonsurveyresult',
            old_name='user_id',
            new_name='respondent',
        ),
        migrations.RenameField(
            model_name='comparisonsurveyresult',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='passedsurvey',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='passedsurvey',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rateobject',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.AddField(
            model_name='comparisonsurvey',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comparisonsurvey',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
