# Generated by Django 3.2 on 2021-05-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison_survey', '0003_auto_20210517_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonsurvey',
            name='top_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comparisonsurvey',
            name='description',
            field=models.TextField(help_text='words are free... but not more than 500 symbols', max_length=500),
        ),
        migrations.AlterField(
            model_name='comparisonsurvey',
            name='topic',
            field=models.CharField(help_text='create catchy topics...', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reason',
            field=models.TextField(help_text='please indicate the reason for the complaint', max_length=100),
        ),
        migrations.AlterField(
            model_name='rateobject',
            name='description',
            field=models.TextField(help_text='rate object name here...', max_length=50),
        ),
        migrations.AlterField(
            model_name='rateobject',
            name='media',
            field=models.CharField(help_text='url of image here...', max_length=150),
        ),
    ]
