# Generated by Django 3.2 on 2021-05-23 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparison_survey', '0004_auto_20210518_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='entertainment', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='comparisonsurvey',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comparison_survey.category'),
            preserve_default=False,
        ),
    ]
