# Generated by Django 3.2 on 2021-05-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison_survey', '0007_auto_20210523_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateobject',
            name='description',
            field=models.CharField(help_text='rate object name here...', max_length=50),
        ),
    ]
