# Generated by Django 3.2 on 2021-06-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison_survey', '0008_alter_rateobject_description'),
    ]

    operations = [
    ]
